version: 2.1
jobs:
  semgrep-full-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep full scan"
          command: |
            echo "this is not a pull request"
            semgrep ci
  semgrep-pr-scan:
    parameters:
      default_branch:
        type: string
        default: main
    environment:
      SEMGREP_BASELINE_REF: << parameters.default_branch >>
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep pull request scan"
          command: |
            echo "this is a pull request scan"
            echo "My parameter value is << parameters.default_branch >>"
            echo 'export SEMGREP_COMMIT=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export SEMGREP_PR_ID=${CIRCLE_PULL_REQUEST##*/}' >> $BASH_ENV
            echo 'export SEMGREP_JOB_URL=${CIRCLE_BUILD_URL}' >> $BASH_ENV
            echo 'export SEMGREP_REPO_NAME=${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
            echo 'export SEMGREP_REPO_URL=${CIRCLE_REPOSITORY_URL}' >> $BASH_ENV
            echo 'export SEMGREP_BRANCH=${CIRCLE_BRANCH}' >> $BASH_ENV
            echo 'export SEMGREP_APP_TOKEN=$SEMGREP_APP_TOKEN' >> $BASH_ENV
            echo ${CIRCLE_SHA1}
            echo ${CIRCLE_PULL_REQUEST##*/}
            echo ${CIRCLE_BUILD_URL}
            echo ${CIRCLE_PROJECT_REPONAME}
            echo ${CIRCLE_REPOSITORY_URL}
            echo ${CIRCLE_BRANCH}
            echo $SEMGREP_BASELINE_REF
            git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            semgrep ci
workflows:
  version: 2
  scan:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: main
          context:
            - dev
      - semgrep-pr-scan:
          filters:
            branches:
              ignore: main          
          context:
            - dev