version: 2.1
jobs:
  semgrep-full-scan-main-branch:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep full scan to main branch"
          command: |
            apt-get update
            apt-get install -y curl
            echo "This is a semgrep full scan to main branch"
            PR_URL=$CIRCLE_PULL_REQUEST
            PR_ID=${PR_URL##*/}
            echo "Pull Request ID: $PR_ID"
            echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
            echo "CIRCLE_BUILD_URL: $CIRCLE_BUILD_URL"
            echo "CIRCLE_PREVIOUS_BUILD_NUM: $CIRCLE_PREVIOUS_BUILD_NUM"
            echo "pipeline.git.branch: << pipeline.git.branch >>"
            echo "pipeline.trigger_source: << pipeline.trigger_source >>"
            echo "pipeline.git.revision: << pipeline.git.revision >>"
            # Get the latest commit hash on the main branch
            LATEST_COMMIT=$(git rev-parse main)
            # Make a request to the CircleCI API to fetch the previous build details
            PREVIOUS_BUILD=$(curl --header "Circle-Token: CIRCLECI_API_TOKEN" \
                     --url "https://circleci.com/api/v2/project/github/r2c-CSE/test-semgrep-pro/pipeline?branch=main&filter=successful&limit=2")
            # Extract the pull request ID from the previous build details
            PREVIOUS_PR_ID=$(echo "$PREVIOUS_BUILD" | jq -r ".items[1].pull_requests[0].number")
            echo "Previous Pull Request ID: $PREVIOUS_PR_ID"
            semgrep ci
  semgrep-diff-scan-feature-branch:
    parameters:
      default_branch:
        type: string
        default: main
    environment:
      SEMGREP_BASELINE_REF: << parameters.default_branch >>
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep full scan to feature branch"
          command: |
            echo "This is a diff scan to feature branch"
            git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            semgrep ci
workflows:
  version: 2
  scan:
    jobs:
      - semgrep-full-scan-main-branch:
          filters:
            branches:
              only: main
          context:
            - dev
      - semgrep-diff-scan-feature-branch:
          filters:
            branches:
              ignore: main          
          context:
            - dev