version: 2.1
jobs:
  semgrep-full-scan-main-branch:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep full scan to main branch"
          command: |
            echo "This is a semgrep full scan to main branch"
            PR_URL=$CIRCLE_PULL_REQUEST
            PR_ID=${PR_URL##*/}
            echo "Pull Request ID: $PR_ID"
            echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
            echo "CIRCLE_BUILD_URL: $CIRCLE_BUILD_URL"
            echo "CIRCLE_PREVIOUS_BUILD_NUM: $CIRCLE_PREVIOUS_BUILD_NUM"
            echo "pipeline.git.branch: << pipeline.git.branch >>"
            echo "pipeline.trigger_source: << pipeline.trigger_source >>"
            echo "pipeline.git.revision: << pipeline.git.revision >>"
            semgrep ci
  semgrep-diff-scan-feature-branch:
    parameters:
      default_branch:
        type: string
        default: main
    environment:
      SEMGREP_BASELINE_REF: << parameters.default_branch >>
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "Semgrep full scan to feature branch"
          command: |
            echo "This is a diff scan to feature branch"
            git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            semgrep ci
workflows:
  version: 2
  scan:
    jobs:
      - semgrep-full-scan-main-branch:
          filters:
            branches:
              only: main
          context:
            - dev
      - semgrep-diff-scan-feature-branch:
          filters:
            branches:
              ignore: main          
          context:
            - dev